{
 "title": "FastAPI + Prometheus",
 "refresh": "10s",
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total[5m]))"
    }
   ]
  },
  {
   "title": "Requests Over Time",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 0, "w": 18, "h": 9 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{method}} {{path}}" }
   ]
  },
  {
   "title": "Requests by Status Code",
   "type": "barchart",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 9 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (status)"
    }
   ]
  },
  {
   "title": "In-Progress Requests",
   "type": "gauge",
   "gridPos": { "x": 12, "y": 4, "w": 6, "h": 4 },
   "targets": [
    { "expr": "http_requests_in_progress" }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 13, "w": 24, "h": 9 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])"
    }
   ]
  }
 ]
}